#! /usr/bin/env python
#
# git-squeeze
# Copyright (c) Ryan Kadwell <ryan@riaka.ca>
#
# Sample git plugin
#
# To use this command as `git squeeze` you would simply need to add this bin
# folder to your path.
#
# Author: Ryan Kadwell <ryan@riaka.ca>
#

import squeeze

# Some dummy handlers to see how they are setup
def handle_add(delta, *files):
   print "ADDED " + files[0]

def handle_remove(delta, *files):
   print "DELETED " + files[0]

def handle_add_remove(delta, *files):
   print "ADDED or DELETED " + files[0]

def handle_modify(delta, *files):
   print "MODIFIED " + files[0]

def handle_rename(delta, *files):
   print "RENAMED " + files[0] + " -> " + files[1]

s = squeeze.Squeeze()

# Function will be called when a file addition is detected
s.add_handler(handle_add, squeeze.FILE_ADDED)

# Function will be called when a file addition or deletion is detected.
s.add_handler(handle_add_remove, squeeze.FILE_ADDED | squeeze.FILE_DELETED)

s.add_handler(handle_remove, squeeze.FILE_DELETED)
s.add_handler(handle_modify, squeeze.FILE_MODIFIED)
s.add_handler(handle_rename, squeeze.FILE_RENAMED)

s.run()
